window_resolutions:
    - &uhd [2400, 1200]
    - &hd  [1200, 600]
    - &hdp [1800, 900]

image_resolutions:
    - &ir_8   8x8
    - &ir_16  16x16
    - &ir_32  32x32
    - &ir_64  64x64
    - &ir_128 128x128
    - &ir_256 256x256

data_dirs:
    - &dd_1  GQN_SimpleRoom
    - &dd_2  GQN_SimpleRoom_withobj
    - &dd_3  GQN_SimpleRoom_RandomizedObjects_2
    - &dd_4  GQN_SimpleRoom_nocolorchange-oneobject
    - &dd_5  GQN_SimpleRoom_nocolorchange-oneobject-randompositioned
    - &dd_6  GQN_SimpleRoom_no_variation
    - &dd_7  GQN_SimpleRoom_rand-sky-color
    - &dd_8  GQN_SimpleRoom_sphere_rand_‎pos
    - &dd_9  GQN_SimpleRoom_sphere_rand_‎pos+rand_sky
    - &dd_10 GQN_SimpleRoom_colorchange-skyandwalls
    - &dd_11 1_GQN_SR_rand_sky+walls(samecolor)
    - &dd_12 WS-3-ChangingObjectunity
    - &dd_13 WS-4-goodTextures
    - &dd_14 WS-5-FloorTex+
    - &dd_15 ObjectInvariance_1
    - &dd_16 ObjectInvariance_2_moreSticks
    - &dd_17 WS-6-Ceaner
    - &dd_18 WS-6-Ceaner_NF

model_paths:
  - &mp_0  ~
  - &mp_1  date=2018-11-09_time=20-06-34-982949_name=Joe-Cruz_version=1_id=8419_idim=(32-32).hdf5
  - &mp_2  date=2018-11-10_time=02-04-25-643243_name=Walter-Meltzer_version=1_id=5155.hdf5
  - &mp_3  date=2018-11-10_time=04-01-37-084561_name=Allen-Sullivan_version=1_id=8980.hdf5
  - &mp_4  date=2018-11-10_time=19-38-46-521301_name=Cynthia-Westfall_version=1_id=4765.hdf5
  - &mp_5  date=2018-11-10_time=23-52-03-966682_name=Michelle-Zenon_version=1_id=6702.hdf5
  - &mp_6  date=2018-11-11_time=00-49-55-331805_name=Susan-Rhoads_version=1_id=2031.hdf5
  - &mp_7  date=2018-11-11_time=05-05-40-479640_name=Andrew-Fernandez_version=1_id=4284.hdf5
  - &mp_8  date=2018-11-11_time=08-29-17-546315_name=Nina-Flores_version=1_id=7394.hdf5
  - &mp_9  date=2018-11-11_time=08-53-34-708542_name=Darin-Brown_version=2_id=1107.hdf5
  - &mp_10 date=2018-11-11_time=19-13-35-540088_name=Joseph-Howell_version=1_id=9420.hdf5
  - &mp_11 date=2018-12-08_time=16-30-40-306150_env=WS-3-ChangingObjectunity_name=Ruth-Baron_version=1_id=9170
  - &mp_12 date=2018-12-08_time=22-03-09-435703_env=WS-5-FloorTex+_name=Jesse-Mcwethy_version=5_id=6807
  - &mp_13 date=2018-12-09_time=00-15-02-616311_env=WS-5-FloorTex+_name=Herbert-Rodriguez_version=2_id=3434
  - &mp_14 date=2018-12-10_time=17-01-00-586787_env=WS-6-Ceaner_name=Dana-Guffey_version=4_id=8459
  - &mp_15 date=2018-12-15_time=20-08-25-512816_env=WS-6-Ceaner-NF_name=Jerry-Higgins_version=1_id=1818

param_spec:
  model_to_generate:      multi    # to generate if no model loaded
  num_input_observations: 4
  epochs:                 1
  batch_size:             32
  data_multiplier:        0.3
  log_frequency:          10
  save_frequency:         30
  train:                  true
  black_n_white:          false

data_spec:
  model_load_path:        *mp_0
  data_dir:               *dd_18
  image_resolution:       *ir_32
  window_resolution:      *hdp

run_spec:
  fast_debug_mode:        false    # load less data and dont save model
  run_environment:        true
  run_pygame:             false
  udp_image_send_port:    8686


